(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "CONTROLEILUMINACAO"
   "<CONTROLEILUMINACAO-REQUEST>"
   "CONTROLEILUMINACAO-REQUEST"
   "<CONTROLEILUMINACAO-RESPONSE>"
   "CONTROLEILUMINACAO-RESPONSE"
  ))

