// Generated by gencpp from file beginner_tutorials/Ambiente.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_AMBIENTE_H
#define BEGINNER_TUTORIALS_MESSAGE_AMBIENTE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Ambiente_
{
  typedef Ambiente_<ContainerAllocator> Type;

  Ambiente_()
    : temperatura(0.0)
    , umidade(0.0)  {
    }
  Ambiente_(const ContainerAllocator& _alloc)
    : temperatura(0.0)
    , umidade(0.0)  {
  (void)_alloc;
    }



   typedef float _temperatura_type;
  _temperatura_type temperatura;

   typedef float _umidade_type;
  _umidade_type umidade;





  typedef boost::shared_ptr< ::beginner_tutorials::Ambiente_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Ambiente_<ContainerAllocator> const> ConstPtr;

}; // struct Ambiente_

typedef ::beginner_tutorials::Ambiente_<std::allocator<void> > Ambiente;

typedef boost::shared_ptr< ::beginner_tutorials::Ambiente > AmbientePtr;
typedef boost::shared_ptr< ::beginner_tutorials::Ambiente const> AmbienteConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Ambiente_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Ambiente_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::Ambiente_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Ambiente_<ContainerAllocator2> & rhs)
{
  return lhs.temperatura == rhs.temperatura &&
    lhs.umidade == rhs.umidade;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::Ambiente_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Ambiente_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Ambiente_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Ambiente_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Ambiente_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Ambiente_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Ambiente_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Ambiente_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Ambiente_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34ba80ca03e34a8cd5a9afb761234652";
  }

  static const char* value(const ::beginner_tutorials::Ambiente_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34ba80ca03e34a8cULL;
  static const uint64_t static_value2 = 0xd5a9afb761234652ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Ambiente_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Ambiente";
  }

  static const char* value(const ::beginner_tutorials::Ambiente_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Ambiente_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 temperatura\n"
"float32 umidade\n"
"\n"
;
  }

  static const char* value(const ::beginner_tutorials::Ambiente_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Ambiente_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temperatura);
      stream.next(m.umidade);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ambiente_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Ambiente_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Ambiente_<ContainerAllocator>& v)
  {
    s << indent << "temperatura: ";
    Printer<float>::stream(s, indent + "  ", v.temperatura);
    s << indent << "umidade: ";
    Printer<float>::stream(s, indent + "  ", v.umidade);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_AMBIENTE_H
