// Generated by gencpp from file beginner_tutorials/ControleIluminacaoResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_CONTROLEILUMINACAORESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_CONTROLEILUMINACAORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct ControleIluminacaoResponse_
{
  typedef ControleIluminacaoResponse_<ContainerAllocator> Type;

  ControleIluminacaoResponse_()
    : resposta()  {
    }
  ControleIluminacaoResponse_(const ContainerAllocator& _alloc)
    : resposta(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _resposta_type;
  _resposta_type resposta;





  typedef boost::shared_ptr< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ControleIluminacaoResponse_

typedef ::beginner_tutorials::ControleIluminacaoResponse_<std::allocator<void> > ControleIluminacaoResponse;

typedef boost::shared_ptr< ::beginner_tutorials::ControleIluminacaoResponse > ControleIluminacaoResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::ControleIluminacaoResponse const> ControleIluminacaoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.resposta == rhs.resposta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59415f2556b55ab9879d7fd7b2bbab3b";
  }

  static const char* value(const ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59415f2556b55ab9ULL;
  static const uint64_t static_value2 = 0x879d7fd7b2bbab3bULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/ControleIluminacaoResponse";
  }

  static const char* value(const ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string resposta\n"
"\n"
;
  }

  static const char* value(const ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resposta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControleIluminacaoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::ControleIluminacaoResponse_<ContainerAllocator>& v)
  {
    s << indent << "resposta: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.resposta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_CONTROLEILUMINACAORESPONSE_H
