// Generated by gencpp from file beginner_tutorials/ControleIluminacao.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_CONTROLEILUMINACAO_H
#define BEGINNER_TUTORIALS_MESSAGE_CONTROLEILUMINACAO_H

#include <ros/service_traits.h>


#include <beginner_tutorials/ControleIluminacaoRequest.h>
#include <beginner_tutorials/ControleIluminacaoResponse.h>


namespace beginner_tutorials
{

struct ControleIluminacao
{

typedef ControleIluminacaoRequest Request;
typedef ControleIluminacaoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControleIluminacao
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::ControleIluminacao > {
  static const char* value()
  {
    return "dd563be63c4578244cd65e069bc1911e";
  }

  static const char* value(const ::beginner_tutorials::ControleIluminacao&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::ControleIluminacao > {
  static const char* value()
  {
    return "beginner_tutorials/ControleIluminacao";
  }

  static const char* value(const ::beginner_tutorials::ControleIluminacao&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::ControleIluminacaoRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::ControleIluminacao >
template<>
struct MD5Sum< ::beginner_tutorials::ControleIluminacaoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::ControleIluminacao >::value();
  }
  static const char* value(const ::beginner_tutorials::ControleIluminacaoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::ControleIluminacaoRequest> should match
// service_traits::DataType< ::beginner_tutorials::ControleIluminacao >
template<>
struct DataType< ::beginner_tutorials::ControleIluminacaoRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::ControleIluminacao >::value();
  }
  static const char* value(const ::beginner_tutorials::ControleIluminacaoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::ControleIluminacaoResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::ControleIluminacao >
template<>
struct MD5Sum< ::beginner_tutorials::ControleIluminacaoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::ControleIluminacao >::value();
  }
  static const char* value(const ::beginner_tutorials::ControleIluminacaoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::ControleIluminacaoResponse> should match
// service_traits::DataType< ::beginner_tutorials::ControleIluminacao >
template<>
struct DataType< ::beginner_tutorials::ControleIluminacaoResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::ControleIluminacao >::value();
  }
  static const char* value(const ::beginner_tutorials::ControleIluminacaoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_CONTROLEILUMINACAO_H
