// Generated by gencpp from file beginner_tutorials/ControleIluminacaoRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_CONTROLEILUMINACAOREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_CONTROLEILUMINACAOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct ControleIluminacaoRequest_
{
  typedef ControleIluminacaoRequest_<ContainerAllocator> Type;

  ControleIluminacaoRequest_()
    : comando()  {
    }
  ControleIluminacaoRequest_(const ContainerAllocator& _alloc)
    : comando(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _comando_type;
  _comando_type comando;





  typedef boost::shared_ptr< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ControleIluminacaoRequest_

typedef ::beginner_tutorials::ControleIluminacaoRequest_<std::allocator<void> > ControleIluminacaoRequest;

typedef boost::shared_ptr< ::beginner_tutorials::ControleIluminacaoRequest > ControleIluminacaoRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::ControleIluminacaoRequest const> ControleIluminacaoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.comando == rhs.comando;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20735899cef58c19fdb13abb7f9d907e";
  }

  static const char* value(const ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20735899cef58c19ULL;
  static const uint64_t static_value2 = 0xfdb13abb7f9d907eULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/ControleIluminacaoRequest";
  }

  static const char* value(const ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string comando\n"
;
  }

  static const char* value(const ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.comando);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControleIluminacaoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::ControleIluminacaoRequest_<ContainerAllocator>& v)
  {
    s << indent << "comando: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.comando);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_CONTROLEILUMINACAOREQUEST_H
