// Generated by gencpp from file beginner_tutorials/Funcionarios.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_FUNCIONARIOS_H
#define BEGINNER_TUTORIALS_MESSAGE_FUNCIONARIOS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Funcionarios_
{
  typedef Funcionarios_<ContainerAllocator> Type;

  Funcionarios_()
    : nome()
    , idade(0)
    , cargo()
    , altura(0.0)  {
    }
  Funcionarios_(const ContainerAllocator& _alloc)
    : nome(_alloc)
    , idade(0)
    , cargo(_alloc)
    , altura(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _nome_type;
  _nome_type nome;

   typedef int8_t _idade_type;
  _idade_type idade;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cargo_type;
  _cargo_type cargo;

   typedef double _altura_type;
  _altura_type altura;





  typedef boost::shared_ptr< ::beginner_tutorials::Funcionarios_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Funcionarios_<ContainerAllocator> const> ConstPtr;

}; // struct Funcionarios_

typedef ::beginner_tutorials::Funcionarios_<std::allocator<void> > Funcionarios;

typedef boost::shared_ptr< ::beginner_tutorials::Funcionarios > FuncionariosPtr;
typedef boost::shared_ptr< ::beginner_tutorials::Funcionarios const> FuncionariosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Funcionarios_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Funcionarios_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::Funcionarios_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Funcionarios_<ContainerAllocator2> & rhs)
{
  return lhs.nome == rhs.nome &&
    lhs.idade == rhs.idade &&
    lhs.cargo == rhs.cargo &&
    lhs.altura == rhs.altura;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::Funcionarios_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Funcionarios_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Funcionarios_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Funcionarios_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Funcionarios_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Funcionarios_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Funcionarios_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Funcionarios_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Funcionarios_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f599a6c815b91d516a23de2962c57921";
  }

  static const char* value(const ::beginner_tutorials::Funcionarios_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf599a6c815b91d51ULL;
  static const uint64_t static_value2 = 0x6a23de2962c57921ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Funcionarios_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Funcionarios";
  }

  static const char* value(const ::beginner_tutorials::Funcionarios_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Funcionarios_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string nome\n"
"int8 idade\n"
"string cargo\n"
"float64 altura\n"
;
  }

  static const char* value(const ::beginner_tutorials::Funcionarios_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Funcionarios_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nome);
      stream.next(m.idade);
      stream.next(m.cargo);
      stream.next(m.altura);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Funcionarios_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Funcionarios_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Funcionarios_<ContainerAllocator>& v)
  {
    s << indent << "nome: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.nome);
    s << indent << "idade: ";
    Printer<int8_t>::stream(s, indent + "  ", v.idade);
    s << indent << "cargo: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cargo);
    s << indent << "altura: ";
    Printer<double>::stream(s, indent + "  ", v.altura);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_FUNCIONARIOS_H
