#!/usr/bin/env python

from __future__ import print_function

from beginner_tutorials.srv import AddTwoInts,AddTwoIntsResponse
import rospy

def controle(requisito):
    global estado
    if requisito.comando == 
    print("Returning [%s + %s = %s]"%(req.a, req.b, (req.a + req.b)))
    return AddTwoIntsResponse(req.a + req.b)

def add_two_ints_server():
    rospy.init_node('iluminacao_server')
    s = rospy.Service('iluminacao_server', ControleIluminca, controle)
    rospy.spin()



if __name__ == "__main__":   
    global estado
    estado = 0
    add_two_ints_server()
